"""
- The Driver File
- Handles User Input
- Display Current Game State object
"""

import pygame as p
from Chess import ChessEngine

global colors

p.init()
WIDTH = HEIGHT = 512 # or 400 are good resolutions
DIMENSION = 8 # 8x8 Board
SQ_SIZE = HEIGHT // DIMENSION
MAX_FPS = 15 #For animations
IMAGES = {}

'''
Only want to render images once
Will initialze a global dictionary of images
Will be called exactly once within main
'''


def loadImages():
    pieces = ['wP', 'wR', 'wB', 'wN', 'wK', 'wQ', 'bP', 'bR', 'bB', 'bN', 'bK', 'bQ']
    for piece in pieces:
        IMAGES[piece] = p.transform.scale(p.image.load("images/" + piece + ".png"), (SQ_SIZE, SQ_SIZE))
    # We can access an image by --> IMAGES['wP']


'''
The main driver
- Will handle User Input
_ Will handle updating graphics
'''


def main():
    p.init()
    screen = p.display.set_mode((WIDTH, HEIGHT))
    clock = p.time.Clock()
    screen.fill(p.Color("white"))
    gameState = ChessEngine.GameState()
    validMoves = gameState.getValidMoves()
    moveMade = False # Flag Variable for when a VALID move is made
    animate = False # Flag variable for when a move should be animated
    loadImages() # Done only once since before loop
    running = True
    sqSelected = () # No square initially selected, keeps track of the last click of the user (tuple: (row, col))
    playerClicks = [] # Keeps track of player clicks (two tuples: [(6,4), (4,4)])
    gameOver = False
    playerOne = True # If a Human is playing white, then this will be true, If an AI is playing than false
    playerTwo = False # Same for black
    while running:
        humanTurn = (gameState.whiteToMove and playerOne) or (not gameState.whiteToMove and playerTwo)
        for e in p.event.get():
            if e.type == p.QUIT:
                running = False
            # Mouse Handler
            elif e.type == p.MOUSEBUTTONDOWN:
                if not gameOver and humanTurn:
                    location = p.mouse.get_pos() # (x,y) location of mouse
                    row = location[1] // SQ_SIZE
                    col = location[0]//SQ_SIZE
                    '''
                    if gameState.board[row, col] == "--" and len(playerClicks) == 0:
                        continue
                    '''
                    if sqSelected == (row, col): # the user clicked the same square again
                        sqSelected = () # Deselects
                        playerClicks = []
                    else:
                        sqSelected = (row, col)
                        playerClicks.append(sqSelected) # Append for both first and second clicks
                    if len(playerClicks) == 2: # After the second click
                        move = ChessEngine.Move(playerClicks[0], playerClicks[1], gameState.board)
                        print(move.getChessNotation())
                        # This will be the move generated by the engine
                        for i in range(len(validMoves)):
                            if move == validMoves[i]:
                                gameState.makeMove(validMoves[i])
                                moveMade = True
                                animate = True
                                sqSelected = () # Rest user clicks
                                playerClicks = []
                        if not moveMade:
                            playerClicks = [sqSelected]

            # Key Handlers
            elif e.type == p.KEYDOWN:
                if e.key == p.K_z: # Undo when 'z' is pressed
                    gameState.undoMove()
                    moveMade = True
                    animate = False
                if e.key == p.K_r: # Reset the board when 'r' is pressed
                    gameState = ChessEngine.GameState()
                    validMoves = gameState.getValidMoves()
                    sqSelected = ()
                    playerClicks = []
                    moveMade = False
                    animate = False


        if moveMade:
            if animate:
                animateMove(gameState.moveLog[-1], screen, gameState.board, clock)
            validMoves = gameState.getValidMoves()
            moveMade = False
            animate = False

        drawGameState(screen, gameState, validMoves, sqSelected)

        if gameState.checkmate:
            gameOver = True
            if gameState.whiteToMove:
                drawText(screen, 'White got bodied!')
            else:
                drawText(screen, 'Black got bodied!')
        elif gameState.stalemate:
            gameOver = True
            drawText(screen, 'Stalemate!')

        clock.tick(MAX_FPS)
        p.display.flip()

'''
Highlight square selected, and moves available for piece selected
'''

def highlightSqaures(screen, gameState, validMoves, sqSelected):
    if sqSelected != ():
        row, col = sqSelected
        # Check that sqSelceted is a piece that ca be moved by whoever turn it is (aka their own piece)
        if gameState.board[row][col][0] == ('w' if gameState.whiteToMove else 'b'):
            # Highlight Selected Square
            square = p.Surface((SQ_SIZE, SQ_SIZE))
            square.set_alpha(100)
            square.fill(p.Color('red'))
            screen.blit(square, (col * SQ_SIZE, row * SQ_SIZE))
            # Highlight moves from that square
            square.fill(p.Color('yellow'))
            for move in validMoves:
                if move.startRow == row and move.startCol == col:
                    screen.blit(square, (SQ_SIZE * move.endCol, SQ_SIZE * move.endRow))




'''
Responsible for graphics within a current gameState
'''


def drawGameState(screen, gameState, validMoves, sqSelected):
    drawBoard(screen) # Draws squares on the board
    highlightSqaures(screen, gameState, validMoves, sqSelected)
    drawPieces(screen, gameState.board) # Draw pieces on top of board



'''
Draw the squares on the board
'''


def drawBoard(screen):
    global colors
    colors = [p.Color("light gray"), p.Color("dark green")]
    for row in range(DIMENSION):
        for col in range(DIMENSION):
            color = colors[((row+col) % 2)]
            p.draw.rect(screen, color, p.Rect(col*SQ_SIZE, row*SQ_SIZE, SQ_SIZE, SQ_SIZE))


'''
Draw the pieces on the board using the GameState.board
'''


def drawPieces(screen, board):
    for row in range(DIMENSION):
        for col in range(DIMENSION):
            piece = board[row][col]
            if piece != "--": # Not an empty square
                # Used to draw an image over an image
                screen.blit(IMAGES[piece], p.Rect(col*SQ_SIZE, row*SQ_SIZE, SQ_SIZE, SQ_SIZE))


'''
Animating a move
'''

def animateMove(move, screen, board, clock):
    global colors
    deltaRow = move.endRow - move.startRow
    deltaCol = move.endCol - move.startCol
    framesPerSquare = 10 # Frames to move one square
    frameCount = (abs(deltaRow) + abs(deltaCol)) * framesPerSquare
    for frame in range(frameCount + 1):
        row, col = (move.startRow + deltaRow * (frame / frameCount), move.startCol + deltaCol * (frame / frameCount))
        drawBoard(screen)
        drawPieces(screen, board)
        # Need to erase pieceMoved from ending square because it's animated in initially
        color = colors[(move.endRow + move.endCol) % 2]
        endSquare = p.Rect(move.endCol * SQ_SIZE, move.endRow * SQ_SIZE, SQ_SIZE, SQ_SIZE)
        p.draw.rect(screen, color, endSquare)
        # Draw Captured Piece onto rectangle
        if move.pieceCaptured != '--':
            screen.blit(IMAGES[move.pieceCaptured], endSquare)
        # Draw moving piece
        screen.blit(IMAGES[move.pieceMoved], p.Rect(col * SQ_SIZE, row * SQ_SIZE, SQ_SIZE, SQ_SIZE))
        p.display.flip()
        clock.tick(60)

def drawText(screen, text):
    font = p.font.SysFont("Helvitca", 50, True, False)
    textObject = font.render(text, 0, p.Color("white"))
    textLocation = p.Rect(0, 0, WIDTH, HEIGHT).move(WIDTH / 2 - textObject.get_width() / 2,
                                                    HEIGHT / 2 - textObject.get_height() / 2) # Centering text
    screen.blit(textObject, textLocation)
    textObject = font.render(text, 0, p.Color('Black'))
    screen.blit(textObject, textLocation.move(2, 2))



if __name__ == "__main__":
    main()
